### PR TITLE
Fix warnings (mt 5.8+) due to disallowed filenames

### PR DESCRIPTION
**Pull request by Niklp09**
Move blend files from `/models/` to `/util/blender/`

Caused by mt https://github.com/minetest/minetest/pull/13711

### CODE REVIEW

**Comment by wsor4035** [comment]
Iirc can't one use gitattributes or something to exclude files from the cdb package? Might be worth doing here. Will check on this later, otherwise looks fine

**Comment by Niklp09** [comment]
> Iirc can't one use gitattributes or something to exclude files from the cdb package?

Some people (like me) don't use cdb to get their mods

**Comment by wsor4035** [comment]
> > Iirc can't one use gitattributes or something to exclude files from the cdb package?
> 
> Some people (like me) don't use cdb to get their mods

yeah, i know, but for the people who do, would make sense to remove it to shrink the package size. those who want them can just git clone

**Comment by Niklp09** [comment]
done (docs: https://github.com/minetest/contentdb/blob/master/app/flatpages/help/package_config.md#excluding-files)

**Review by wsor4035 — APPROVED** [review]
makes sense, thanks

**Comment by Rash3089** [comment]
> Iirc can't one use gitattributes or something to exclude files from the cdb package? Might be worth doing here. Will check on this later, otherwise looks fine

**Review by Rash3089 — COMMENTED** [review]
Yyyyy

**Pull request merged**
