### PR TITLE
Fix out-of-bounds textures in `[combine`

### LINKED ISSUE #24: out-of-bounds combine textures
The ~~server~~ client log is spammed with these:

```
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (258,17) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (174,34) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (255,51) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (255,17) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (147,51) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (275,51) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (263,34) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (271,34) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (256,17) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (256,34) for [combine
2024-02-03 09:41:29: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (258,34) for [combine
2024-02-03 09:41:31: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (258,0) for [combine
2024-02-03 09:41:31: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (270,0) for [combine
2024-02-03 09:41:31: WARNING[Main]: generateImagePart(): Skipping "signs_lib_color_16px_n.png" as it's out-of-bounds (258,0) for [combine
```

### PR DESCRIPTION
**Pull request by OgelGames**
Fixes #24 by preventing character and fill textures from being added past the end of each line of text.

### CODE REVIEW

**Review by Niklp09 — APPROVED** [review]
Works, I prefer this over #25.

**Comment by appgurueu** [comment]
Why? I'm not convinced keeping the `fill_line` hack is a good idea; I don't see why it would be needed for the `signs_lib` functionality, and it surely is inefficient.

To me, the other PR cuts down on the mess and dirty hacks, while this PR adds further complexity. Assuming both ultimately implement the same features correctly, why prefer this PR?

I'd also be interested in hearing what @tenplus1 thinks.

**Comment by tenplus1** [comment]
@appgurueu is corrent, while this may work it adds further complexity and sticks with the old masking method of sign creation that was hacky to begin with.  The updated method in #25 only has to draw the coloured text itself which results in faster creation of signage.

**Comment by OgelGames** [comment]
Neither method is significantly better or worse than the other, and it's definitely not a hack to use masking to color the text.

The biggest difference is that this PR fixes the cause of the out-of-bounds textures, preventing overflowing text from being added to the texture.

**Comment by OgelGames** [comment]
It's been 2 weeks, merging this.

**Pull request merged**
